-- CNEC Korea Corporate Platform Schema

-- 1. corporate_accounts 테이블 생성
-- 이 테이블은 Supabase auth.users와 1:1 관계를 가지며, 기업 및 관리자 계정의 추가 정보를 저장합니다.
CREATE TABLE IF NOT EXISTS public.corporate_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    business_registration_number TEXT NOT NULL UNIQUE,
    company_name TEXT NOT NULL,
    representative_name TEXT NOT NULL,
    start_date TEXT, -- 개업일자
    phone_number TEXT,
    address TEXT,
    is_approved BOOLEAN NOT NULL DEFAULT FALSE, -- 관리자 승인 여부
    is_admin BOOLEAN NOT NULL DEFAULT FALSE, -- 관리자 여부
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. RLS (Row Level Security) 활성화
ALTER TABLE public.corporate_accounts ENABLE ROW LEVEL SECURITY;

-- 3. 정책 (Policies) 설정

-- 3.1. SELECT 정책
-- 인증된 사용자는 자신의 계정 정보만 조회할 수 있습니다.
-- 관리자는 모든 계정 정보를 조회할 수 있습니다.
DROP POLICY IF EXISTS "Allow individual read access" ON public.corporate_accounts;
CREATE POLICY "Allow individual read access"
    ON public.corporate_accounts FOR SELECT
    USING (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "Allow admin read access" ON public.corporate_accounts;
CREATE POLICY "Allow admin read access"
    ON public.corporate_accounts FOR SELECT
    TO authenticated
    USING ( (SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE );

-- 3.2. INSERT 정책
-- 모든 사용자가 회원가입(계정 정보 생성)을 할 수 있도록 허용합니다.
-- auth_user_id는 현재 로그인한 사용자의 ID와 일치해야 합니다.
DROP POLICY IF EXISTS "Allow insert for all users" ON public.corporate_accounts;
CREATE POLICY "Allow insert for all users"
    ON public.corporate_accounts FOR INSERT
    WITH CHECK (auth.uid() = auth_user_id);

-- 3.3. UPDATE 정책
-- 사용자는 자신의 계정 정보만 수정할 수 있습니다.
-- 관리자는 모든 계정 정보를 수정할 수 있습니다.
DROP POLICY IF EXISTS "Allow individual update access" ON public.corporate_accounts;
CREATE POLICY "Allow individual update access"
    ON public.corporate_accounts FOR UPDATE
    USING (auth.uid() = auth_user_id)
    WITH CHECK (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "Allow admin update access" ON public.corporate_accounts;
CREATE POLICY "Allow admin update access"
    ON public.corporate_accounts FOR UPDATE
    TO authenticated
    USING ( (SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE );

-- 3.4. DELETE 정책
-- 보안을 위해 클라이언트에서의 직접적인 삭제는 허용하지 않습니다.
-- 필요한 경우 관리자 또는 서버 측에서 처리합니다.
DROP POLICY IF EXISTS "Disallow delete for all users" ON public.corporate_accounts;
CREATE POLICY "Disallow delete for all users"
    ON public.corporate_accounts FOR DELETE
    USING (FALSE);

-- 4. 관리자 계정 생성 함수 (필요 시 사용)
-- Supabase SQL Editor에서 직접 실행하여 초기 관리자 계정을 생성할 수 있습니다.
/*
CREATE OR REPLACE FUNCTION create_admin_user(
    admin_username TEXT,
    admin_password TEXT
)
RETURNS TEXT AS $$
DECLARE
    user_id UUID;
BEGIN
    -- 1. Auth User 생성
    INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, recovery_token, recovery_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_sent_at, confirmed_at)
    VALUES (current_setting(\'auth.instance_id\')::UUID, uuid_generate_v4(), \'authenticated\', \'authenticated\', admin_username || \'@admin.cnecbiz.com\', crypt(admin_password, gen_salt(\'bf\')), NOW(), \'\', NULL, NULL, \'{\"provider\":\"email\",\"providers\":[\"email\"]}\', \'{}\', NOW(), NOW(), \'\', \'\', NULL, NOW())
    RETURNING id INTO user_id;

    -- 2. corporate_accounts에 관리자 정보 추가
    INSERT INTO public.corporate_accounts (auth_user_id, business_registration_number, company_name, representative_name, is_approved, is_admin)
    VALUES (user_id, \'000-00-00000\', \'CNEC Admin\', admin_username, TRUE, TRUE);

    RETURN \'Admin user created successfully with ID: \' || user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 함수 실행 예시 (username: admin, password: securepassword123)
-- SELECT create_admin_user(\'admin\', \'securepassword123\');
*/

-- 5. updated_at 자동 갱신 트리거
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_corporate_accounts_update ON public.corporate_accounts;
CREATE TRIGGER on_corporate_accounts_update
    BEFORE UPDATE ON public.corporate_accounts
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();


