-- 다중 브랜드 지원을 위한 브랜드 테이블 생성
CREATE TABLE IF NOT EXISTS public.brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporate_account_id BIGINT NOT NULL REFERENCES public.corporate_accounts(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    logo_url TEXT,
    description TEXT,
    website TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 기존 corporate_accounts 테이블의 brand_name 필드를 brands 테이블로 마이그레이션
DO $$
DECLARE
    account_record RECORD;
BEGIN
    -- 기존 corporate_accounts 테이블에서 brand_name이 있는 레코드 조회
    FOR account_record IN 
        SELECT id, brand_name FROM public.corporate_accounts 
        WHERE brand_name IS NOT NULL AND brand_name != ''
    LOOP
        -- 해당 계정에 대한 브랜드 레코드 생성
        INSERT INTO public.brands (corporate_account_id, name)
        VALUES (account_record.id, account_record.brand_name);
    END LOOP;
END $$;

-- 캠페인 테이블에 brand_id 필드 추가
ALTER TABLE public.campaigns
ADD COLUMN IF NOT EXISTS brand_id BIGINT REFERENCES public.brands(id) ON DELETE SET NULL;

-- RLS (Row Level Security) 설정
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;

-- 기업 사용자는 자신의 브랜드만 조회/수정 가능
CREATE POLICY "Companies can view their own brands"
    ON public.brands FOR SELECT
    USING ((SELECT corporate_accounts.auth_user_id FROM public.corporate_accounts WHERE corporate_accounts.id = brands.corporate_account_id) = auth.uid());

CREATE POLICY "Companies can insert their own brands"
    ON public.brands FOR INSERT
    WITH CHECK ((SELECT corporate_accounts.auth_user_id FROM public.corporate_accounts WHERE corporate_accounts.id = corporate_account_id) = auth.uid());

CREATE POLICY "Companies can update their own brands"
    ON public.brands FOR UPDATE
    USING ((SELECT corporate_accounts.auth_user_id FROM public.corporate_accounts WHERE corporate_accounts.id = brands.corporate_account_id) = auth.uid());

CREATE POLICY "Companies can delete their own brands"
    ON public.brands FOR DELETE
    USING ((SELECT corporate_accounts.auth_user_id FROM public.corporate_accounts WHERE corporate_accounts.id = brands.corporate_account_id) = auth.uid());

-- 관리자는 모든 브랜드 조회/수정 가능
CREATE POLICY "Admins can view all brands"
    ON public.brands FOR SELECT
    USING ((SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE);

CREATE POLICY "Admins can update all brands"
    ON public.brands FOR UPDATE
    USING ((SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE);

CREATE POLICY "Admins can delete all brands"
    ON public.brands FOR DELETE
    USING ((SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE);

-- updated_at 자동 갱신 트리거 설정
CREATE TRIGGER on_brands_update
    BEFORE UPDATE ON public.brands
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_brands_corporate_account_id ON public.brands(corporate_account_id);
