-- CNEC 인증 시스템 개선 및 캠페인/결제 시스템 구축을 위한 데이터베이스 스키마 수정
-- 작성일: 2025-10-15

-- 1. corporate_accounts 테이블 수정
-- 사업자등록번호 UNIQUE 제약 조건 제거 및 이메일 컬럼 추가
ALTER TABLE public.corporate_accounts
    DROP CONSTRAINT IF EXISTS corporate_accounts_business_registration_number_key;

-- 이메일 컬럼이 없는 경우에만 추가
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'corporate_accounts' 
        AND column_name = 'email'
    ) THEN
        ALTER TABLE public.corporate_accounts
            ADD COLUMN email TEXT UNIQUE;
    END IF;
END $$;

-- 브랜드 이름 컬럼 추가 (다중 브랜드 지원)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'corporate_accounts' 
        AND column_name = 'brand_name'
    ) THEN
        ALTER TABLE public.corporate_accounts
            ADD COLUMN brand_name TEXT;
    END IF;
END $$;

-- 2. campaigns 테이블 생성 (캠페인 정보 저장)
CREATE TABLE IF NOT EXISTS public.campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporate_account_id BIGINT NOT NULL REFERENCES public.corporate_accounts(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    reward_amount INTEGER NOT NULL,
    target_platforms JSONB, -- 예: {"instagram": true, "tiktok": true}
    requirements TEXT,
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft', -- draft, active, completed, cancelled
    max_creators INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. campaign_applications 테이블 생성 (크리에이터의 캠페인 신청 정보)
CREATE TABLE IF NOT EXISTS public.campaign_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES public.campaigns(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending', -- pending, approved, rejected, completed
    application_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    approval_date TIMESTAMPTZ,
    completion_date TIMESTAMPTZ,
    sns_post_url TEXT,
    sns_post_engagement JSONB, -- 예: {"likes": 100, "comments": 20, "shares": 5}
    creator_feedback TEXT,
    admin_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. payments 테이블 생성 (기업의 캠페인 비용 결제 정보)
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporate_account_id BIGINT NOT NULL REFERENCES public.corporate_accounts(id) ON DELETE CASCADE,
    campaign_id BIGINT REFERENCES public.campaigns(id) ON DELETE SET NULL,
    amount INTEGER NOT NULL,
    currency TEXT NOT NULL DEFAULT 'JPY',
    payment_method TEXT NOT NULL, -- credit_card, bank_transfer, etc.
    payment_status TEXT NOT NULL DEFAULT 'pending', -- pending, completed, failed, refunded
    payment_date TIMESTAMPTZ,
    payment_reference TEXT, -- 외부 결제 시스템의 참조 ID
    invoice_number TEXT,
    receipt_url TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. transactions 테이블 생성 (모든 금전적 거래 내역)
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_type TEXT NOT NULL, -- payment_in, creator_payment_out, refund, etc.
    amount INTEGER NOT NULL,
    currency TEXT NOT NULL DEFAULT 'JPY',
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    corporate_account_id BIGINT REFERENCES public.corporate_accounts(id) ON DELETE SET NULL,
    campaign_id BIGINT REFERENCES public.campaigns(id) ON DELETE SET NULL,
    payment_id BIGINT REFERENCES public.payments(id) ON DELETE SET NULL,
    application_id BIGINT REFERENCES public.campaign_applications(id) ON DELETE SET NULL,
    transaction_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    description TEXT,
    status TEXT NOT NULL DEFAULT 'completed', -- pending, completed, failed
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. RLS (Row Level Security) 설정
-- campaigns 테이블에 대한 RLS
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;

-- 기업 사용자는 자신이 생성한 캠페인만 조회/수정 가능
CREATE POLICY "Companies can view their own campaigns"
    ON public.campaigns FOR SELECT
    USING ((SELECT corporate_accounts.auth_user_id FROM public.corporate_accounts WHERE corporate_accounts.id = campaigns.corporate_account_id) = auth.uid());

CREATE POLICY "Companies can insert their own campaigns"
    ON public.campaigns FOR INSERT
    WITH CHECK ((SELECT corporate_accounts.auth_user_id FROM public.corporate_accounts WHERE corporate_accounts.id = corporate_account_id) = auth.uid());

CREATE POLICY "Companies can update their own campaigns"
    ON public.campaigns FOR UPDATE
    USING ((SELECT corporate_accounts.auth_user_id FROM public.corporate_accounts WHERE corporate_accounts.id = campaigns.corporate_account_id) = auth.uid());

-- 관리자는 모든 캠페인 조회/수정 가능
CREATE POLICY "Admins can view all campaigns"
    ON public.campaigns FOR SELECT
    USING ((SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE);

CREATE POLICY "Admins can update all campaigns"
    ON public.campaigns FOR UPDATE
    USING ((SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE);

-- campaign_applications 테이블에 대한 RLS
ALTER TABLE public.campaign_applications ENABLE ROW LEVEL SECURITY;

-- 크리에이터는 자신의 신청만 조회/수정 가능
CREATE POLICY "Creators can view their own applications"
    ON public.campaign_applications FOR SELECT
    USING (user_id = auth.uid());

CREATE POLICY "Creators can insert their own applications"
    ON public.campaign_applications FOR INSERT
    WITH CHECK (user_id = auth.uid());

CREATE POLICY "Creators can update their own applications"
    ON public.campaign_applications FOR UPDATE
    USING (user_id = auth.uid());

-- 기업은 자신의 캠페인에 대한 신청만 조회 가능
CREATE POLICY "Companies can view applications for their campaigns"
    ON public.campaign_applications FOR SELECT
    USING ((SELECT corporate_accounts.auth_user_id FROM public.corporate_accounts 
            JOIN public.campaigns ON campaigns.corporate_account_id = corporate_accounts.id 
            WHERE campaigns.id = campaign_applications.campaign_id) = auth.uid());

-- 관리자는 모든 신청 조회/수정 가능
CREATE POLICY "Admins can view all applications"
    ON public.campaign_applications FOR SELECT
    USING ((SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE);

CREATE POLICY "Admins can update all applications"
    ON public.campaign_applications FOR UPDATE
    USING ((SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE);

-- payments 테이블에 대한 RLS
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- 기업은 자신의 결제만 조회 가능
CREATE POLICY "Companies can view their own payments"
    ON public.payments FOR SELECT
    USING ((SELECT auth_user_id FROM public.corporate_accounts WHERE id = payments.corporate_account_id) = auth.uid());

-- 관리자는 모든 결제 조회/수정 가능
CREATE POLICY "Admins can view all payments"
    ON public.payments FOR SELECT
    USING ((SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE);

CREATE POLICY "Admins can update all payments"
    ON public.payments FOR UPDATE
    USING ((SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE);

-- transactions 테이블에 대한 RLS
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- 사용자는 자신과 관련된 거래만 조회 가능
CREATE POLICY "Users can view their own transactions"
    ON public.transactions FOR SELECT
    USING (user_id = auth.uid() OR 
           (corporate_account_id IS NOT NULL AND 
            (SELECT auth_user_id FROM public.corporate_accounts WHERE id = transactions.corporate_account_id) = auth.uid()));

-- 관리자는 모든 거래 조회/수정 가능
CREATE POLICY "Admins can view all transactions"
    ON public.transactions FOR SELECT
    USING ((SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE);

CREATE POLICY "Admins can update all transactions"
    ON public.transactions FOR UPDATE
    USING ((SELECT is_admin FROM public.corporate_accounts WHERE auth_user_id = auth.uid()) = TRUE);

-- 7. updated_at 자동 갱신 트리거 설정
-- campaigns 테이블
CREATE TRIGGER on_campaigns_update
    BEFORE UPDATE ON public.campaigns
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- campaign_applications 테이블
CREATE TRIGGER on_campaign_applications_update
    BEFORE UPDATE ON public.campaign_applications
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- payments 테이블
CREATE TRIGGER on_payments_update
    BEFORE UPDATE ON public.payments
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- transactions 테이블
CREATE TRIGGER on_transactions_update
    BEFORE UPDATE ON public.transactions
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- 8. 기존 corporate_accounts 데이터 마이그레이션 (이메일 필드 채우기)
-- 기존 계정에 대해 사업자등록번호 기반 이메일 생성
UPDATE public.corporate_accounts
SET email = business_registration_number || '@cnecbiz.com'
WHERE email IS NULL;

-- 9. 인덱스 생성 (성능 최적화)
CREATE INDEX IF NOT EXISTS idx_campaigns_corporate_account_id ON public.campaigns(corporate_account_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON public.campaigns(status);
CREATE INDEX IF NOT EXISTS idx_campaign_applications_campaign_id ON public.campaign_applications(campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_applications_user_id ON public.campaign_applications(user_id);
CREATE INDEX IF NOT EXISTS idx_campaign_applications_status ON public.campaign_applications(status);
CREATE INDEX IF NOT EXISTS idx_payments_corporate_account_id ON public.payments(corporate_account_id);
CREATE INDEX IF NOT EXISTS idx_payments_campaign_id ON public.payments(campaign_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON public.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_corporate_account_id ON public.transactions(corporate_account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_campaign_id ON public.transactions(campaign_id);
